project:
  type: website
  output-dir: docs

website:
  title: "Georgia Atkinson"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true



